### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rjworks** [suman-kr/quoters#1]
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/disc/bot/bot-env/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 66, in on_message
    1: Quote.print_anime_quote()
  File "/home/disc/bot/bot-env/lib/python3.8/site-packages/quoters/main.py", line 33, in print_anime_quote
    result = check_connection_and_generate_quote(QuoteType.ANIME_QUOTE)
  File "/home/disc/bot/bot-env/lib/python3.8/site-packages/quoters/extract_data.py", line 34, in check_connection_and_generate_quote
    raise OSError
OSError
```

**Comment by suman-kr** [comment]
I think you didn't have internet connectivity or very slow internet speed while using the package. `OSError` is raised when the package is unable to establish network connectivity. Currently, the package relies on the internet for data.

**Comment by rjworks** [comment]
I’m using vps to run this and there’s internet.

**Comment by suman-kr** [comment]
I've not tried it with any VPS. Are you behind any firewall?. Can you check external IP addresses are allowed from your VPS.

**Comment by rjworks** [comment]
It has worked yesterday but suddenly stopped working today

**Comment by suman-kr** [comment]
That's weird!! Maybe you changed some configuration at your app level which resulted in this error. What are you using this package with?. Can you share more details?

*On a lighter note: `If it works, then don't touch.`*  😄

**Comment by rjworks** [comment]
No, no configurations were changed.

I’m using this for my discord bot. When the bot is mentioned, it will respond with a quote

**Comment by rjworks** [comment]
```
 if bot.user.mentioned_in(message):
        # select which quote to send
        rand = random.randint(0, 1)
        async with message.channel.typing():
            quotes = {
                0: Quote.print(),
                1: Quote.print_anime_quote()
            }
            await asyncio.sleep(1)
        await message.channel.send(quotes[rand])
```

**Comment by suman-kr** [comment]
Everything seems right with your code. Since I'm not able to reproduce the bug, I'll leave the issue open.

**Comment by suman-kr** [comment]
I'll add support for offline in future.

**Comment by rjworks** [comment]
Just tried it on my local machine with strong internet and I get the same error.

**Comment by rjworks** [comment]
I really like this library, I hope this can be fixed.

**Comment by suman-kr** [comment]
Thanks for the appreciation!!. I've pushed the new build. There was a minor problem from my end.
Go ahead and try the new release.

**Comment by rjworks** [comment]
Now I get this
`
“If you only face forward, there is something you will miss seeing.” – Vash the Stampedeif(typeof __ez_fad_position != 'undefined'){__ez_fad_position('div-gpt-ad-bayart_org-large-mobile-banner-2-0')};`

**Comment by suman-kr** [comment]
Yeah, I checked. There were still some bugs regarding data extraction. I've pushed a new build. Hope this solves your problem. 😄

**Comment by suman-kr** [comment]
@rjworks  I've added offline support.
Example:
```py
...
Quote.print_anime_quote(True)
...
```

**Comment by suman-kr** [comment]
@rjworks  I've added support for offline quotes
Example:
```py
...
Quote.print(True)
...
```
